# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Sacha McElligott
email: sacha@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog

title: Home
url: "http://sachaker.github.io"
imgurl: "https://sachaker.github.io/img"

header_pages:
- about
- projects
- research
- other

github_username:  sachaker
minima:
  social_links:
    linkedin: https://www.linkedin.com/in/sacha-mcelligott-136a78a9/

excerpt_separator: <!--exc-->

# Build settings
markdown: kramdown
