# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# theme: minima

# Site settings
author: Sacha McElligott
email: sacha@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog

title: Home
url: "http://sachaker.github.io"
imgurl: "https://sachaker.github.io/img"

# list of links in navbar
navbar-links:
  About: "about"
  Projects: "projects"
  Resume: "resume"
  Other interests: "other"

github_username:  sachaker

social-network-links:
  linkedin: https://www.linkedin.com/in/sacha-mcelligott-136a78a9/

share-links-active:
  linkedin: true
excerpt_separator: <!--exc-->

# Build settings
markdown: kramdown
